#!/usr/bin/env perl

# linode-cli
# Copyright (C) 2013 Linode, LLC

use 5.010;
use strict;
use warnings;

use FindBin;
use lib "$FindBin::RealBin/lib";
use lib '/usr/lib/linode-cli';
use Getopt::Long (qw(:config pass_through));
use Linode::CLI::Util ':basic';

my $object;

if ( defined( $ARGV[0] ) && ( my @found = grep { $_ eq lc( $ARGV[0] ) } @MODES ) ) {
    $object = shift;
}
else {
    GetOptions( 'o|object=s' => \$object ) || die 'Unable to parse options';
}

$object = 'linode'
    unless ( defined($object) && ( my @found = grep { $_ eq $object } @MODES ) );

exec( $FindBin::RealBin . "/linode-$object", @ARGV );
